import { useEffect, useState } from 'react';

const ScholarFeed = () => {
  const [publications, setPublications] = useState([]);

  useEffect(() => {
    // Fetches the JSON file generated by the GitHub Action
    fetch('/scholar.json')
      .then((res) => res.json())
      .then((data) => setPublications(data))
      .catch((err) => console.error("Failed to load publications", err));
  }, []);

  return (
    <div className="w-full">
      {/* Google Scholar Header Imitation */}
      <div className="grid grid-cols-12 gap-4 text-sm font-bold opacity-60 border-b border-gray-300 dark:border-gray-700 pb-2 mb-4">
        <div className="col-span-9">TITLE</div>
        <div className="col-span-2 text-center">CITED BY</div>
        <div className="col-span-1 text-right">YEAR</div>
      </div>

      <div className="space-y-6">
        {publications.map((pub, index) => (
          <div key={index} className="grid grid-cols-12 gap-4 items-start group hover:bg-black/5 dark:hover:bg-white/5 p-2 rounded transition-colors">
            <div className="col-span-9">
              <a href={pub.link} target="_blank" rel="noreferrer" className="text-lg font-semibold text-blue-600 dark:text-blue-400 hover:underline">
                {pub.title}
              </a>
              <div className="text-sm opacity-80 mt-1">{pub.authors}</div>
              <div className="text-sm opacity-60 italic">{pub.journal}</div>
            </div>
            <div className="col-span-2 text-center pt-1 font-mono text-pastel-accent dark:text-dark-accent font-bold">
              {pub.citations || "-"}
            </div>
            <div className="col-span-1 text-right pt-1 opacity-70 font-mono">
              {pub.year}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ScholarFeed;